apiVersion: v1
data:
  linkis.properties: |+
    #
    # Copyright 2019 WeBank
    #
    # Licensed under the Apache License, Version 2.0 (the "License");
    #  you may not use this file except in compliance with the License.
    # You may obtain a copy of the License at
    #
    # http://www.apache.org/licenses/LICENSE-2.0
    #
    # Unless required by applicable law or agreed to in writing, software
    # distributed under the License is distributed on an "AS IS" BASIS,
    # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    # See the License for the specific language governing permissions and
    # limitations under the License.
    #
    wds.linkis.test.mode=true
    wds.linkis.server.version=v1
    wds.linkis.ldap.proxy.url=
    wds.linkis.ldap.proxy.baseDN=
    wds.linkis.server.restful.uri=/
    wds.linkis.server.web.session.timeout=1h
    wds.linkis.gateway.conf.enable.proxy.user=false
    wds.linkis.gateway.conf.url.pass.auth=/dws/
    wds.linkis.gateway.admin.user=root
    wds.linkis.gateway.conf.enable.token.auth=true
    #wds.linkis.gateway.conf.enable.sso=true
    wds.linkis.gateway.conf.enable.cloud-publicservice=true

kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-29T07:58:40Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:linkis-publicservice.properties: {}
    manager: kubectl
    operation: Update
  name: linkis-gateway-config
  namespace: default

