---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "linkis.fullname" . }}-linkis-web-config
data:
  default.conf: |
    server {
                listen       {{ .Values.Web.port }};
                server_name  localhost;
                #charset koi8-r;
                #access_log  /var/log/nginx/host.access.log  main;
                location / {
                root   {{ .Values.linkis.locations.homeDir }}-web;
                index  index.html index.html;
                }

                location /api {
                proxy_pass {{- include "linkis.gateway.url" . | indent 1 }};
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header x_real_ipP $remote_addr;
                proxy_set_header remote_addr $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_http_version 1.1;
                proxy_connect_timeout 4s;
                proxy_read_timeout 600s;
                proxy_send_timeout 12s;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection upgrade;
                }
                #error_page  404              /404.html;
                # redirect server error pages to the static page /50x.html
                #
                error_page   500 502 503 504  /50x.html;
                location = /50x.html {
                root   /usr/share/nginx/html;
                }
            }