---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "linkis.fullname" . }}-mg-gateway
  labels:
    app: {{ include "linkis.fullname" . }}-mg-gateway
    {{- include "linkis.mgGateway.labels" . | nindent 4 }}
  annotations:
    prometheus.io/path: {{ .Values.mgGateway.prometheus.metricsPath }}
    prometheus.io/port: '{{ .Values.mgGateway.port }}'
    prometheus.io/scrape: 'true'
spec:
  ports:
    - name: "http"
      protocol: TCP
      port: {{ .Values.mgGateway.port }}
  selector:
    {{- include "linkis.mgGateway.selectorLabels" . | nindent 4 }}
    app: {{ include "linkis.fullname" . }}-mg-gateway
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  publishNotReadyAddresses: true
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "linkis.fullname" . }}-mg-gateway-headless
  labels:
    app: {{ include "linkis.fullname" . }}-mg-gateway
    {{- include "linkis.mgGateway.labels" . | nindent 4 }}
  annotations:
    prometheus.io/path: {{ .Values.mgGateway.prometheus.metricsPath }}
    prometheus.io/port: '{{ .Values.mgGateway.port }}'
    prometheus.io/scrape: 'true'
spec:
  ports:
    - name: "http"
      protocol: TCP
      port: {{ .Values.mgGateway.port }}
  selector:
    {{- include "linkis.mgGateway.selectorLabels" . | nindent 4 }}
    app: {{ include "linkis.fullname" . }}-mg-gateway
  clusterIP: None
  type: ClusterIP
  publishNotReadyAddresses: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "linkis.fullname" . }}-mg-gateway
  labels:
    app: {{ include "linkis.fullname" . }}-mg-gateway
    version: {{ .Chart.AppVersion }}
    {{- include "linkis.mgGateway.labels" . | nindent 4 }}
  {{- if .Values.mgGateway.annotations }}
  annotations:
    {{- toYaml .Values.mgGateway.annotations | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.mgGateway.replicas }}
  selector:
    matchLabels:
      {{- include "linkis.mgGateway.selectorLabels" . | nindent 6 }}
      app: {{ include "linkis.fullname" . }}-mg-gateway
  template:
    metadata:
      {{- with .Values.mgGateway.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "linkis.fullname" . }}-mg-gateway
        version: {{ .Chart.AppVersion }}
        {{- include "linkis.mgGateway.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: conf
          configMap:
            name: {{ include "linkis.fullname" . }}-linkis-config
        - name: log
          emptyDir: {}
      serviceAccountName: {{ include "linkis.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.mgGateway.podSecurityContext | nindent 8 }}
      containers:
        - name: "gateway"
          securityContext:
            {{- toYaml .Values.mgGateway.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/bash
            - -ecx
            - >-
              RUN_IN_FOREGROUND=true {{ .Values.locations.homeDir }}/sbin/linkis-daemon.sh start mg-gateway
          ports:
            - name: "http"
              containerPort: {{ .Values.mgGateway.port }}
              protocol: TCP
          # TODO: replace with httpGet when spring-boot readiness probe is implemented.
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 20
            failureThreshold: 10
            tcpSocket:
              port: {{ .Values.mgGateway.port }}
          env:
            - name: SERVER_HEAP_SIZE
              value: {{ .Values.mgGateway.jvmHeapSize }}
            - name: EUREKA_URL
              value: {{- include "linkis.registration.url" . | quote | indent 1 }}
            - name: EUREKA_PORT
              value: "{{ .Values.mgEureka.port }}"
            {{- if .Values.mgGateway.envs.extras }}
{{ toYaml .Values.mgGateway.envs.extras | indent 12 }}
            {{- end }}
          {{- if .Values.mgGateway.envs.froms }}
          envFrom:
{{ toYaml .Values.mgGateway.envs.froms | indent 12 }}
          {{- end }}
          volumeMounts:
            - name: conf
              mountPath: {{ .Values.locations.confDir }}
            - name: log
              mountPath: {{ .Values.locations.logDir }}
          resources:
            {{- toYaml .Values.mgGateway.resources | nindent 12 }}
      {{- with .Values.mgGateway.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mgGateway.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mgGateway.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
