---
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Service
metadata:
  name: {{ include "linkis.fullname" . }}-cg-linkismanager
  labels:
    app: {{ include "linkis.fullname" . }}-cg-linkismanager
    {{- include "linkis.cgLinkisManager.labels" . | nindent 4 }}
  annotations:
    prometheus.io/path: {{ .Values.cgLinkisManager.prometheus.metricsPath }}
    prometheus.io/port: '{{ .Values.cgLinkisManager.port }}'
    prometheus.io/scrape: 'true'
spec:
  ports:
    - name: "http"
      protocol: TCP
      port: {{ .Values.cgLinkisManager.port }}
  selector:
    {{- include "linkis.cgLinkisManager.selectorLabels" . | nindent 4 }}
    app: {{ include "linkis.fullname" . }}-cg-linkismanager
  {{- toYaml .Values.svc | nindent 2 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "linkis.fullname" . }}-cg-linkismanager-headless
  labels:
    app: {{ include "linkis.fullname" . }}-cg-linkismanager
    {{- include "linkis.cgLinkisManager.labels" . | nindent 4 }}
  annotations:
    prometheus.io/path: {{ .Values.cgLinkisManager.prometheus.metricsPath }}
    prometheus.io/port: '{{ .Values.cgLinkisManager.port }}'
    prometheus.io/scrape: 'true'
spec:
  ports:
    - name: "http"
      protocol: TCP
      port: {{ .Values.cgLinkisManager.port }}
  selector:
    {{- include "linkis.cgLinkisManager.selectorLabels" . | nindent 4 }}
    app: {{ include "linkis.fullname" . }}-cg-linkismanager
  clusterIP: None
  type: ClusterIP
  publishNotReadyAddresses: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "linkis.fullname" . }}-cg-linkismanager
  labels:
    app: {{ include "linkis.fullname" . }}-cg-linkismanager
    version: {{ .Chart.AppVersion }}
    {{- include "linkis.cgLinkisManager.labels" . | nindent 4 }}
  {{- if .Values.cgLinkisManager.annotations }}
  annotations:
    {{- toYaml .Values.cgLinkisManager.annotations | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.cgLinkisManager.replicas }}
  selector:
    matchLabels:
      {{- include "linkis.cgLinkisManager.selectorLabels" . | nindent 6 }}
      app: {{ include "linkis.fullname" . }}-cg-linkismanager
  template:
    metadata:
      {{- with .Values.cgLinkisManager.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "linkis.fullname" . }}-cg-linkismanager
        version: {{ .Chart.AppVersion }}
        {{- include "linkis.cgLinkisManager.selectorLabels" . | nindent 8 }}
    spec:
      subdomain: {{ include "linkis.fullname" . }}-cg-linkismanager-headless
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: conf
          configMap:
            name: {{ include "linkis.fullname" . }}-linkis-config
        - name: log
          emptyDir: {}
        - name: common
          hostPath:
            path: {{ .Values.linkis.locations.commonDir }}
            type: DirectoryOrCreate
        - name: runtime
          {{- if .Values.linkis.featureGates.localMode }}
          hostPath:
            path: {{ .Values.linkis.locations.hostPath }}
            type: DirectoryOrCreate
          {{- else }}
          emptyDir: {}
          {{- end }}
      serviceAccountName: {{ include "linkis.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.cgLinkisManager.podSecurityContext | nindent 8 }}
      containers:
        - name: "linkismanager"
          securityContext:
            {{- toYaml .Values.cgLinkisManager.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/bash
            - -ecx
            - >-
              EUREKA_PREFER_IP=true RUN_IN_FOREGROUND=true LINKIS_EXTENDED_LIB={{.Values.linkis.locations.commonDir}}/extendlib {{ .Values.linkis.locations.homeDir }}/sbin/linkis-daemon.sh start cg-linkismanager
          ports:
            - name: "http"
              containerPort: {{ .Values.cgLinkisManager.port }}
              protocol: TCP
            {{- if .Values.linkis.featureGates.enableJvmRemoteDebug }}
            - name: "debug"
              containerPort: 5005
              protocol: TCP
            {{- end }}
          # TODO: replace with httpGet when spring-boot readiness probe is implemented.
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 20
            failureThreshold: 10
            tcpSocket:
              port: {{ .Values.cgLinkisManager.port }}
          env:
            {{- if .Values.linkis.featureGates.enableJvmRemoteDebug }}
            - name: DEBUG_PORT
              value: "5005"
            {{- end }}
            - name: SERVER_HEAP_SIZE
              value: {{ .Values.cgLinkisManager.jvmHeapSize }}
            - name: EUREKA_URL
              value: {{- include "linkis.registration.url" . | quote | indent 1 }}
            - name: EUREKA_PREFER_IP
              value: "true"
            - name: EUREKA_PORT
              value: "{{ .Values.mgEureka.port }}"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if .Values.cgLinkisManager.envs.extras }}
{{ toYaml .Values.cgLinkisManager.envs.extras | indent 12 }}
            {{- end }}
          {{- if .Values.cgLinkisManager.envs.froms }}
          envFrom:
{{ toYaml .Values.cgLinkisManager.envs.froms | indent 12 }}
          {{- end }}
          volumeMounts:
            - name: conf
              mountPath: {{ .Values.linkis.locations.confDir }}
            - name: log
              mountPath: {{ .Values.linkis.locations.logDir }}
            - name: runtime
              mountPath: {{ .Values.linkis.locations.runtimeDir }}
            - name: common
              mountPath: {{ .Values.linkis.locations.commonDir }}
          resources:
            {{- toYaml .Values.cgLinkisManager.resources | nindent 12 }}
      {{- with .Values.cgLinkisManager.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cgLinkisManager.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cgLinkisManager.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
