apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkis-manager
  namespace: preprod
  labels:
    app: linkis-manager
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkis-manager
      version: v1
  template:
    metadata:
      labels:
        app: linkis-manager
        version: v1
    spec:
      containers:
        - image: nm.hub.com/luban/linkis-manager:1.0
          imagePullPolicy: Always
          name: linkis-manager
          ports:
            - containerPort: 9106
          lifecycle:
            postStart:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - >
                    cp /etc/security/keytabs/krb5.conf /etc/krb5.conf;
                    cp /etc/security/keytabs/sssd.conf /etc/sssd/sssd.conf;
                    sssd;
                    echo "* */1 * * * /etc/security/keytabs/kinit.sh" >> /var/spool/cron/root;
                    crond;
          env:
            - name: EUREKA_URL
              value: "http://linkis-eureka-service:20303/eureka/"
          volumeMounts:
            - name: log
              mountPath: /opt/linkis/linkis-manager/logs
            - name: linkis-properties
              mountPath: /opt/linkis/linkis-manager/conf/linkis.properties
            - name: kerberos
              mountPath: /etc/security/keytabs/
              readOnly: true
            - name: hadoop-config
              mountPath: /usr/local/hadoop3/etc/hadoop
            - name: hive-config
              mountPath: /usr/local/hive3/conf
            - name: spark-config
              mountPath: /usr/local/spark3/conf
      volumes:
        - name: log
          hostPath:
            path: /data01/rootdir/linkis-1.0/linkis/logs/linkis-manager
        - name: linkis-properties
          hostPath:
            path: /data01/rootdir/linkis-1.0/linkis/config/linkis-manager/linkis.properties
        - name: kerberos
          hostPath:
            path: /data01/rootdir/linkis-1.0/kerberos/
        - name: hadoop-config
          hostPath:
            path: /data01/rootdir/linkis-1.0/ah3/config/hadoop
        - name: hive-config
          hostPath:
            path: /data01/rootdir/linkis-1.0/ah3/config/hive
        - name: spark-config
          hostPath:
            path: /data01/rootdir/linkis-1.0/ah3/config/spark
