server:
  port: 8293
spring:
  application:
    name: mdm-service-hive

eureka:
  client:
    serviceUrl:
      defaultZone: http://${ip}:${port}/eureka/
  instance:
    metadata-map:
      test: wedatasphere

management:
  endpoints:
    web:
      exposure:
        include: refresh,info
logging:
  config: classpath:log4j2.xml


