spring:
  application:
    name: linkis-mg-eureka
  profiles: eureka

server:
  port: 20303
eureka:
  instance:
    hostname:
#    preferIpAddress: true
  client:
#    register-with-eureka: false
#    fetch-registry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:20303/eureka/
#  server:
#    enableSelfPreservation: false
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000
  server:
    response-cache-update-interval-ms: 2000
