server:
  port: 8295
spring:
  application:
    name: mdm-service-elasticsearch

eureka:
  client:
    serviceUrl:
      defaultZone: ${eurekaurl}
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-second: 5
    lease-expiration-duration-in-second: 10
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    metadata-map:
      test: wedatasphere

management:
  endpoints:
    web:
      exposure:
        include: refresh,info
logging:
  config: classpath:log4j2.xml


