apiVersion: v1
kind: Service
metadata:
  name: linkis-mg-gateway
  namespace: preprod
  labels:
    app: linkis-mg-gateway
    service: linkis-mg-gateway
spec:
  ports:
    - name: http
      port: 9001
      targetPort: 9001
      nodePort: 30358
  selector:
    app: linkis-mg-gateway
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkis-mg-gateway
  namespace: preprod
  labels:
    app: linkis-mg-gateway
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkis-mg-gateway
      version: v1
  template:
    metadata:
      labels:
        app: linkis-mg-gateway
        version: v1
    spec:
      containers:
        - image: registry.mydomain.com/library/linkis-mg-gateway:1.2.0
          imagePullPolicy: Always
          name: linkis-mg-gateway
          ports:
            - containerPort: 9001
          lifecycle:
            postStart:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - >
                    \cp /etc/security/keytabs/krb5.conf /etc/krb5.conf;
                    \cp /etc/security/keytabs/sssd.conf /etc/sssd/sssd.conf;
                    sssd;
                    echo "* */1 * * * /etc/security/keytabs/kinit.sh" >> /var/spool/cron/root;
                    crond;
          env:
            - name: EUREKA_URL
              value: "http://linkis-mg-eureka:20303/eureka/"
            - name: START_PORT
              value: "9001"
          volumeMounts:
            - name: log
              mountPath: /opt/linkis/linkis-mg-gateway/logs
            - name: conf
              mountPath: /opt/linkis/linkis-mg-gateway/conf/
            - name: kerberos
              mountPath: /etc/security/keytabs/
              readOnly: true
      volumes:
        - name: log
          hostPath:
            path: /data01/rootdir/linkis-1.0/linkis/logs
        - name: conf
          hostPath:
            path: /data01/rootdir/linkis-1.0/linkis/conf
        - name: kerberos
          hostPath:
            path: /data01/rootdir/linkis-1.0/kerberos/
