apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkis-cg-linkismanager
  namespace: preprod
  labels:
    app: linkis-cg-linkismanager
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkis-cg-linkismanager
      version: v1
  template:
    metadata:
      labels:
        app: linkis-cg-linkismanager
        version: v1
    spec:
      containers:
        - image: registry.mydomain.com/library/linkis-cg-linkismanager:1.2.0
          imagePullPolicy: Always
          name: linkis-cg-linkismanager
          ports:
            - containerPort: 9106
          lifecycle:
            postStart:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - >
                    \cp /etc/security/keytabs/krb5.conf /etc/krb5.conf;
                    \cp /etc/security/keytabs/sssd.conf /etc/sssd/sssd.conf;
                    sssd;
                    echo "* */1 * * * /etc/security/keytabs/kinit.sh" >> /var/spool/cron/root;
                    crond;
          env:
            - name: EUREKA_URL
              value: "http://linkis-mg-eureka:20303/eureka/"
          volumeMounts:
            - name: log
              mountPath: /opt/linkis/linkis-cg-linkismanager/logs
            - name: conf
              mountPath: /opt/linkis/linkis-cg-linkismanager/conf
            - name: kerberos
              mountPath: /etc/security/keytabs/
              readOnly: true
            - name: hadoop-config
              mountPath: /usr/local/hadoop/etc/hadoop
            - name: hive-config
              mountPath: /usr/local/hive/conf
            - name: spark-config
              mountPath: /usr/local/spark/conf
      volumes:
        - name: log
          hostPath:
            path: /data01/rootdir/linkis-1.0/linkis/logs
        - name: conf
          hostPath:
            path: /data01/rootdir/linkis-1.0/linkis/conf
        - name: kerberos
          hostPath:
            path: /data01/rootdir/linkis-1.0/kerberos/
        - name: hadoop-config
          hostPath:
            path: /data01/rootdir/linkis-1.0/ah3/config/hadoop
        - name: hive-config
          hostPath:
            path: /data01/rootdir/linkis-1.0/ah3/config/hive
        - name: spark-config
          hostPath:
            path: /data01/rootdir/linkis-1.0/ah3/config/spark
