server:
  port: 8293
spring:
  application:
    name: linkis-ps-metadatamanager-hive

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:20303/eureka/
  instance:
    metadata-map:
      test: wedatasphere

management:
  endpoints:
    web:
      exposure:
        include: refresh,info
logging:
  config: classpath:log4j2.xml


